/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Include/typedefs.h"
#include "../Include/keypad.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SIZE 12

enum EVENT {
	READKEY = 0,
	NONE = 1,
};

void noEvent(void) {
	return;
}

void (*TaskTable[])(void) = {
		[READKEY] = KeyPad_Task,
		[NONE] = noEvent,
};

enum EVENT buffer[SIZE];
uint8_t write = 0;
uint8_t read = 0;
uint8_t count = 0;

void produce(enum EVENT event) {
	if(count == SIZE) {
		return;
	}

	buffer[write] = event;
	write = (write + 1) % SIZE;
	count++;
}

enum EVENT consume(void) {
	if(count == 0) {
		return NONE;
	}

	enum EVENT data = buffer[read];
	read = (read + 1) % SIZE;
	count--;
	return data;

}

int isFull(void) {
	return count == SIZE;
}

int isEmpty(void) {
	return count == 0;
}

void EXTI9_5_IRQHandler(void) {
	if(EXTI->PR & (1 << 5)) {
		EXTI->PR |= (1 << 5);
		produce(READKEY);
	}

	if(EXTI->PR & (1 << 6)) {
		EXTI->PR |= (1 << 6);
		produce(READKEY);
	}

	if(EXTI->PR & (1 << 7)) {
		EXTI->PR |= (1 << 7);
		produce(READKEY);
	}

	if(EXTI->PR & (1 << 8)) {
		EXTI->PR |= (1 << 8);
		produce(READKEY);
	}
}

void dispatch(void) {
	while(1) {
		if(!isEmpty()) {
			enum EVENT event = consume();

			TaskTable[event]();

		}
	}
}

int main(void) {
	CLK_INIT();
	KEYPAD_INIT();
	EXTI_INIT();
	dispatch();

}
